### ISSUE TITLE
Failed to run in ovos

### ISSUE THREAD

**Issue by Stormfollower** [OVOSHatchery/ovos-skill-iss-location#1]
I didn't try it in mycroftai first.

Just adding it to the skills.list got me the following error:

`Collecting git+https://github.com/JarbasSkills/skill-iss-location.git (from -r /home/ovos/.config/mycroft/skills.list (line 3))
  Cloning https://github.com/JarbasSkills/skill-iss-location.git to /tmp/pip-req-build-16ei2gf_
  Running command git clone --filter=blob:none --quiet https://github.com/JarbasSkills/skill-iss-location.git /tmp/pip-req-build-16ei2gf_
  Resolved https://github.com/JarbasSkills/skill-iss-location.git to commit 9497bbae3b9e6f9723f29848ed155807fd5cbf1b
ERROR: git+https://github.com/JarbasSkills/skill-iss-location.git (from -r /home/ovos/.config/mycroft/skills.list (line 3)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
`

**Comment by JarbasAl** [comment]
this skill is not yet packaged or updated for OVOS, so it can not be installed the same way as others, it needs to be manually installed mycroft style

**Comment by JarbasAl** [comment]
one year later, it has been updated
